### ISSUE TITLE
Python path broken under Linux

### ISSUE THREAD

**Issue by notfood** [nimadez/mental-diffusion#10]
This line fails on Linux due to the path:

https://github.com/nimadez/mental-diffusion/blob/56c388515ec5a08857bc5cfaebda370a193e2ede/src/extension.js#L51

My ComfyUI install doesn't have a python_embeded folder. Ideally it should be using the venv's python. If this could be specified by setting variable, it'd work for both Linux and Windows.

**Comment by nimadez** [comment]
MD updated to support user-defined Python path, please update, thank you.

**Comment by notfood** [comment]
There appears to be an error on the update.

https://github.com/nimadez/mental-diffusion/blob/7ae90be35954fbdcb23c70458cfa4e3ea9b0313c/src/extension.js#L55

It has an additional ComfyUI in the path, causing it to execute instead: `. . ./ComfyUI/ComfyUI/main.py`

Note the double ComfyUI

**Comment by nimadez** [comment]
MD updated, user must specify ComfyUI source-code directory instead of root directory, please let me know if the problem is solved.

**Comment by notfood** [comment]
There must be a race condition or something. When I run ComfyUI standalone, Checkpoint and VAE combo boxes are populated correctly, when I allow the extension to start ComfyUI (it starts correctly), it doesn't populate them, no matter what I do.

ComfyUI folder: `/media/Makai/home/Projects/AI/ComfyUI`

With Python path: `source /media/Makai/home/Projects/AI/ComfyUI/venv/bin/activate && python`
Models won't load:
![image](https://github.com/nimadez/mental-diffusion/assets/5370107/c4cd1fb5-b37f-46ee-8b76-aa5de2bcd61b)

With Python path: `/bin/false` and pre-starting ComfyUI
Models load:
![image](https://github.com/nimadez/mental-diffusion/assets/5370107/3e0a545c-18cc-41b2-b508-2a73d8871128)

The issue has been fixed, but a different one arose.

**Comment by nimadez** [comment]
Checkpoints are received from the ComfyUI server, this problem has nothing to do with paths. It is probably related to your ComfyUI installation method. I am looking for the cause of the problem to find a solution.

**Comment by nimadez** [comment]
Checkpoints are received from the ComfyUI server, this problem has nothing to do with paths. I am looking for the cause of the problem to find a solution, but unfortunately I have not yet been able to reproduce the new issue.

**Comment by notfood** [comment]
Yeah, seems strange to me, the start commands look the same, ComfyUI starts correctly, binds to the port just fine, but it won't populate the combo boxes. Pressing Generate will send the command to ComfyUI but it'll complain that there is no model in the inputs while the MD UI waits forever. I'll be pre-starting ComfyUI in the meantime.
