### ISSUE TITLE
Asking for clarification about using the interface

### ISSUE THREAD

**Issue by ShmuelRonen** [nimadez/mental-diffusion#2]
Hi...
Thanks for the opportunity to use your intriguing development.

I installed MentalDifffusion and everything seems to be working fine.
I was able to understand how to create images in Text2Img but I didn't crack the way how to create Inpainting and Outpainting and I also didn't understand how to use LoRa.

The direction looks promising and I am happy about this experience.

**Comment by nimadez** [comment]
Thank you for your feedback,
**_LoRA_** is not supported yet but it's on my to-do list,
There is no button to enable **_inpainting_**, If you put an image in both slots (Input Image and Mask Image), the pipeline switches to inpainting.
**_Outpainting_** is a trick for inpainting, there is no pipeline for outpainting,
To create outpainting, set "Outpaint Padding" size, your initial image and mask will be generated for you.

**Comment by nimadez** [comment]
Thank you for your feedback,
LoRA is not supported yet but it's on my to-do list.
There is no button to enable inpainting, If you put an image in both slots (Input Image and Mask Image), the pipeline switches to inpainting.
Outpainting is a trick for inpainting, there is no pipeline for outpainting,
To create outpainting, set "Outpaint Padding" size, your initial image and mask will be generated for you.

**Comment by nimadez** [comment]
Thank you for your feedback,
**_LoRA_** is not supported yet but it's on my to-do list,
There is no button to enable **_inpainting_**, If you put an image in both slots (Input Image and Mask Image), the pipeline switches to inpainting.
**_Outpainting_** is a trick for inpainting, there is no pipeline for outpainting,
To create outpainting, set "Outpaint Padding" size, your initial image and mask will be generated for you.

**Comment by ShmuelRonen** [comment]
Thank you very much for the explanation. I was able to perform Inpainting and Image to Image. But I can't find the Outpaint Padding option.

**Comment by ShmuelRonen** [comment]
I find now the Outpaint Padding in the mask. I can add a number. but I dont understand out to use it.

**Comment by nimadez** [comment]
After setting the padding size, you are ready to do the inpainting, there is nothing left to do!
There are many artifacts in this method, and to solve these problems you need to use the Mask tool with some more inpaints.

**Comment by ShmuelRonen** [comment]
Something happens that I don't know if you meant. When I choose to create an image of size 512 x 512 for example, and choose the Upscale x4 option after the image has been created in Dimensions it says 2048 x 2048 and then if I click on Text2Image the software will try to increase this size by 4 times and declare a lack of memory.

**Comment by ShmuelRonen** [comment]
Thanks! now it works perffect 4 me
