### ISSUE TITLE
Dimensions numbers not fixed

### ISSUE THREAD

**Issue by ShmuelRonen** [nimadez/mental-diffusion#3]
Something happens that I don't know if you meant. When I choose to create an image of size 512 x 512 for example, and choose the Upscale x4 option after the image has been created the Dimensions numbers change to 2048 x 2048 and then if I click on Text2Image again the software will try to increase this size by 4 times and declare a lack of memory.

That means I have to manually return it to 512 x 512 every time

**Comment by nimadez** [comment]
In my opinion, auto-upscaling is not very interesting, it was more of an experimental feature, auto-upscaling has been removed.

**Comment by ShmuelRonen** [comment]
I did to your project some publicity:

https://www.facebook.com/groups/stableaisrael/posts/789528682896352/

**Comment by nimadez** [comment]
Thank you for your kindness. If you have any suggestions or problems, please let me know.
