### ISSUE TITLE
Issue with loading checkpoints list

### ISSUE THREAD

**Issue by jamesanto** [nimadez/mental-diffusion#7]
I am using ComfyUI windows portable version (latest). The get_object_info endpoint returns just checkpoint names and it doesn't have the `checkpoints\\` prefix. As of now checkpoints list is loaded only if it has that prefix. So, for me the checkpoints list is always empty.

BTW, love this interface. I think it's much better than ComfyBox and StableSwarmUI

**Comment by nimadez** [comment]
The problem was found, I used the "extra_model_paths.yaml" file to define the path of ComfyUI checkpoints. If you copy the checkpoints into the "models" directory in the ComfyUI folder, the ```checkpoints\\``` prefix is missing.
Thank you, the problem will be fixed soon.

**Comment by nimadez** [comment]
Problem solved, please update or reinstall.

**Comment by jamesanto** [comment]
It works now, thank you!
