### ISSUE TITLE
Support for dynamic tags/inputs similar to StableSwarmUI

### ISSUE THREAD

**Issue by jamesanto** [nimadez/mental-diffusion#8]
StableSwarmUI has a feature where you can prefix a node's title with `SwarmUI:` and it's automatically converted and available as an input. I am assuming that the current `tags` feature works similar to that except that we need to edit the JSON workflow to tag the inputs. Is it possible to do something similar to StableSwarmUI where we can prefix the node title with `MD:` or `MentalDiffusion:` and it would automatically be converted to an input in the UI?

But eventually, we would need some sort of metadata supported for each node(changes required in ComfyUI) and we should use the metadata to automatically recognise the inputs

**Comment by jamesanto** [comment]
BTW, raised a feature request on the ComfyUI repo to support node level metadata: https://github.com/comfyanonymous/ComfyUI/issues/1305

**Comment by nimadez** [comment]
I'm closing this issue as unsolved because there is currently no user-friendly solution, but I look forward to ComfyUI updates.
